databases:
  - name: investors-db
    databaseName: investors
    user: investors_user
    plan: free

services:
  - type: web
    name: investors-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: investors-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
